### ISSUE TITLE
Crash when using

### ISSUE THREAD

**Issue by emyfops** [Coderx-Gamer/lectern-crash#5]
`01:24:41.456
Textures payload has been tampered with (signature invalid)
01:24:41.549
Caught exception in thread Thread[Worker-Main-11,5,main]
java.lang.IllegalArgumentException: Name and ID cannot both be blank
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:200)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:187)
	at net.minecraft.class_1071.method_4653(class_1071.java:100)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)`

**Comment by Coderx-Gamer** [comment]
The mod does not mess with anything in the stacktrace you provided I believe, could be other mods you are using causing this.

**Comment by MrBreakNFix** [comment]
xd
